### ISSUE TITLE
[BUG?] Ancient Guardian doesn't spawn

### ISSUE THREAD

**Issue by EODTex** [lassiterm/AM2R-Multitroid#24] opened 2021-02-18 07:39 UTC
In the updates Ancient Guardian's spawn is tied to the Golden Temple log. In playing with solo normal game with save warps, I saved by the breeding grounds before going into Golden Temple proper, got all the items I needed and killed the metroid there, save warped (and by doing so making it so I didn't have the log), finished off the rest of the metroids and exited. This caused Ancient Guardian not to spawn, which may be an unintended consequence, but is working as expected since logs are not shared and his spawn is tied to logs now.

Version 1.1.2

**Comment by Miepee** [comment] 2021-02-18 13:38
This should be fixed in the development repo already.
Logs should be shared now, which makes this bug not appear anymore.

**Comment by lassiterm** [comment] 2021-02-19 23:07
The issue is fixed, but logs as a whole are still not shared. This specific log will be synced through means of custom events so as not to add any unnecessarily higher internet speed requirements.

**Closed by lassiterm** 2021-02-19 23:07 UTC
Labels: bug
